version: '3.6'
services:
  db_prod:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'chatop_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'chatop'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'openclassrooms'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'openclassrooms'
    ports:
      - '3306:3306'
    expose:
      - '3306'
